### ISSUE TITLE
Upgrade react-scripts to v5, Support Webpack 5.x

### ISSUE THREAD

**Issue by jaywcjlove** [kktjs/kkt#198]
Upgrade [`react-scripts`](https://www.npmjs.com/package/react-scripts) [![react-scripts version](https://img.shields.io/npm/v/react-scripts.svg)](https://www.npmjs.com/package/react-scripts)

- https://github.com/kktjs/kkt/issues/325
- https://github.com/kktjs/kkt/issues/324
- https://github.com/kktjs/kkt/issues/313
- https://github.com/kktjs/kkt/issues/305
- https://github.com/facebook/create-react-app/pull/11201
- fix(@kkt/less-modules): fix postcss options errors. 549f6fc
- fix(@kkt/stylus-modules): fix rules options errors #198.

**Comment by jaywcjlove** [comment]
e3ac95fe219a68e0f03f9259863aa27ba8399de4
f2a44331b762c242f95d322df7d96954b7df7f41
36eb963fac3850be8d2c8c8ed8ef27ff9642332a

**Comment by jaywcjlove** [comment]
TypeError: Cannot read property 'javascript' of undefined
https://github.com/webpack-contrib/terser-webpack-plugin/issues/339

**Comment by jaywcjlove** [comment]
https://github.com/facebook/create-react-app/pull/11201

**Comment by jaywcjlove** [comment]
- https://github.com/kktjs/kkt/issues/305

**Comment by jaywcjlove** [comment]
- https://github.com/jaywcjlove/validator.js/commit/d5710ede1262afbf7c14d6358d5dd6029809992f

**Comment by jaywcjlove** [comment]
> - https://github.com/uiwjs/react-code-preview/runs/4673097348?check_suite_focus=true

```shell
> kkt build --app-src ./website

Creating an optimized production build...
Failed to compile.

Error: true is not a PostCSS plugin
    at runMicrotasks (<anonymous>)
```

- chore: add package-lock.json file. https://github.com/uiwjs/react-code-preview/commit/700567d8c05ad7349f237eb1b494685b7f5f5fee

**Comment by jaywcjlove** [comment]
```bash
Module not found: Error: Can't resolve 'path' in '/home/runner/work/react-amap/react-amap/node_modules/@uiw/react-code-preview/node_modules/@babel/core/lib/transformation'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
```

https://github.com/uiwjs/react-amap/runs/4749457776?check_suite_focus=true

**Comment by jaywcjlove** [comment]
```shell
Creating an optimized production build...
Compiled with warnings.

./node_modules/@babel/standalone/babel.js
Critical dependency: the request of a dependency is an expression

./node_modules/@babel/standalone/babel.js
Critical dependency: the request of a dependency is an expression
```

临时解决方案

```shell
$ CI=false npm run doc
```

```js
module.exports = {
  //...
  module: {
    exprContextCritical: true,
  },
};
```

- https://webpack.js.org/configuration/module/#module-contexts
- https://stackoverflow.com/a/65857316/1334703

**Comment by jaywcjlove** [comment]
- https://github.com/facebook/create-react-app/pull/11932
- https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896

```bash
KKT:BUILD:ERROR: TypeError: MiniCssExtractPlugin is not a constructor
    at createWebpackConfig (/home/runner/work/react-code-preview/react-code-preview/node_modules/react-scripts/config/webpack.config.js:664:9)
    at _callee$ (/home/runner/work/react-code-preview/react-code-preview/node_modules/kkt/src/scripts/build.ts:31:29)
    at tryCatch (/home/runner/work/react-code-preview/react-code-preview/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/runner/work/react-code-preview/react-code-preview/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/runner/work/react-code-preview/react-code-preview/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/runner/work/react-code-preview/react-code-preview/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/runner/work/react-code-preview/react-code-preview/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

```bash
npm i mini-css-extract-plugin@2.4.5 -D
```
